### ISSUE TITLE
SyntaxError: invalid syntax in File "/workspace/mxnet_benchmarks/benchmarks.py", line 390

### ISSUE THREAD

**Issue by bingws** [HewlettPackard/dlcookbook-dlbs#11]
hi,Here I come again.I used the mxnet framework, there was a syntax error.
my  command：
```
 python $experimenter run --log-level=warning -Pexp.framework='"mxnet"' -Pexp.gpus='0'  \
-Pexp.docker=true -Pmonitor.frequency=0.1 -Vexp.replica_batch='[16]' -Pexp.num_warmup_batches=10\
-Pexp.num_batches=10 -Pmxnet.cudnn_autotune='"false"' -Vexp.model='["alexnet"]' \
-Pexp.phase='"training"'  \
-Pexp.log_file='"${BENCH_ROOT}/mxnet/${exp.model}_${exp.effective_batch}.log"'\
-Pmxnet.docker_image='"nvcr.io/nvidia/mxnet:18.11-py3"'
```

error:
```
__results.start_time__= "2018-12-18:08:54:20:839"
  File "/workspace/mxnet_benchmarks/benchmarks.py", line 390
    except Exception, e:
                    ^
SyntaxError: invalid syntax
```
@sergey-serebryakov

**Comment by sergey-serebryakov** [comment]
@bingws,
Hi and thanks for reporting on this! We've been discussing this for quite some time and I think we now have more reasons to finally fix it. This error is caused by the fact that most of DLBS code is only Python2 compatible.  You are using a python3 mxnet package `nvcr.io/nvidia/mxnet:18.11-py3` that caused that error. 

I added [ad-hoc fixes](https://github.com/HewlettPackard/dlcookbook-dlbs/commit/b29a7b06a0f56441f61941b39e681d0a089041dd) that may solve this but cannot really test because my development machine has older generation of GPU that is not compatible with this docker image and right now I do not have access to our lab. I'll take a closer look tonight and will reply in this thread. 

In any case, even if my fixes work, I cannot guarantee that DLBS code will be compatible with that particular version of MXNET in that container (as I mentioned, I will test it tonight). We've been running benchmarks with reference image `dlbs/mxnet:18.11` and with NGC image `nvcr.io/nvidia/mxnet:18.05-py2`. These two MXNET images should be compatible with DLBS.

**Comment by sergey-serebryakov** [comment]
So, I ran the latest DLBS version:
```bash
source ./scripts/environment.sh
/usr/bin/python $experimenter run --log-level=warning -Pexp.framework='"mxnet"' -Pexp.gpus='0' -Pexp.docker=true -Pmonitor.frequency=0.1 -Vexp.replica_batch='[16]' -Pexp.num_warmup_batches=10 -Pexp.num_batches=10 -Pmxnet.cudnn_autotune='"false"' -Vexp.model='["alexnet"]' -Pexp.phase='"training"' -Pexp.log_file='"${DLBS_ROOT}/benchmarks/mxnet_test.log"' -Pmxnet.docker_image='"nvcr.io/nvidia/mxnet:18.11-py3"'
```
and it worked, at least, with AlexNet model. I will add to my TODO list making DLBS Python3 compatible.

**Comment by bingws** [comment]
@sergey-serebryakov Thanks very much. I would like to ask you a question. When TensorFlow benchmark was tested, you said AlexNetOWT was a version of AlexNet before. Is there any difference between them?

**Comment by sergey-serebryakov** [comment]
@bingws, There's a small difference between AlexNet ([graph](http://ethereon.github.io/netscope/#/gist/5c94a074f4e4ac4b81ee28a796e04b5d), [example code](https://github.com/HewlettPackard/dlcookbook-dlbs/blob/master/python/nvcnn_benchmarks/nvcnn.py#L880)) and AlexNetOWT ([graph](http://ethereon.github.io/netscope/#/gist/dc85cc15d59d720c8a18c4776abc9fd5), [example code](https://github.com/HewlettPackard/dlcookbook-dlbs/blob/master/python/nvcnn_benchmarks/nvcnn.py#L905)) implementations. The difference is basically the following:

1. AlexNetOWT does not use LRN (Local Response Normalization) layer.
2. They have different number of channels in convolutional layers:
      ```bash
      AlexNet:    96 - 256 - 384 - 384 - 256
      AlexNetOWT: 64 - 192 - 384 - 256 - 256
      ```
We decided to use these two models because we had found out that in reported benchmark results, the `AlexNet` title referred to AlexNet in one cases and AlexNetOWT in others making things a little bit confusing in terms of comparison.

Based on my observations, AlexNetOWT (`-Pexp.model='"alexnet_owt'"`) implementation is the one that is widely used by benchmarkers.
